version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: ./.env
  redis:
    image: redis:alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
      - "1025:1025"
  celery:
    build:
      context: .
    command: celery -A tamarcado worker -Q celery --loglevel=INFO
    env_file:
      - ./.env
    depends_on:
      - app
      - redis
