# Generated by Django 4.0.2 on 2022-04-17 17:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                ("data_horario", models.DateTimeField()),
                ("nome_cliente", models.CharField(max_length=255)),
                ("email_cliente", models.EmailField(max_length=254)),
                ("telefone_cliente", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
