# Generated by Django 4.0.2 on 2022-05-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_alter_endereco_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=12, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='prestador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to=settings.AUTH_USER_MODEL, verbose_name='Prestador'),
        ),
    ]
